### ISSUE TITLE
Contact us Page shows a big blurry image. 

### ISSUE THREAD

**Issue by sharidass1408** [tirumalasrija/WebMobileZ-March2018#1]
**Contact use page has a big blur image. Either please remove it and replace it with proper size image.**

![2019-05-11_5-25-28](https://user-images.githubusercontent.com/1563192/57567842-51c65680-73ad-11e9-8bb7-9c5016f5610c.png)

**Comment by pvenkateshnaidu** [comment]
we need ask ui designer

**Comment by tirumalasrija** [comment]
removed image
