### ISSUE TITLE
About Us page has AVS Consultants. Replace it with proper content.

### ISSUE THREAD

**Issue by sharidass1408** [tirumalasrija/WebMobileZ-March2018#12]
"About Us" page has AVS Consultants. Replace it with an proper image or content. 

![2019-05-11_6-06-18](https://user-images.githubusercontent.com/1563192/57568269-f13a1800-73b2-11e9-9d80-f0033badef9b.png)

**Comment by pvenkateshnaidu** [comment]
Updated
