### ISSUE TITLE
Replace Image in the Services Tab with the following Image

### ISSUE THREAD

**Issue by sharidass1408** [tirumalasrija/WebMobileZ-March2018#16]
We have this beautiful work flow diagram at the website
https://www.invisionapp.com/enterprise

Please replace 
![image](https://user-images.githubusercontent.com/1563192/57588367-3a888580-74e1-11e9-8ade-17b2e132aa78.png)

with this

![image](https://user-images.githubusercontent.com/1563192/57588347-e1b8ed00-74e0-11e9-9496-8fae9ab643e9.png)

**Comment by pvenkateshnaidu** [comment]
Updated
