### ISSUE TITLE
MBHomeCare link is broke

### ISSUE THREAD

**Issue by sharidass1408** [tirumalasrija/WebMobileZ-March2018#2]
MBHomeCare link is broke either fix it or remove it from the website.
 

  http://universitiesconnect.com/MBHomecare/

![2019-05-11_5-27-54](https://user-images.githubusercontent.com/1563192/57567870-9eaa2d00-73ad-11e9-80ef-b053c598c8a1.png)

**Comment by pvenkateshnaidu** [comment]
we don't have url so removed from our website
