### ISSUE TITLE
Moosangles.com is still Saying it is Very Risky. Talk with SiteLock

### ISSUE THREAD

**Issue by sharidass1408** [tirumalasrija/WebMobileZ-March2018#3]
When you click on mooseangles.com you get the below error. We have an account with SiteLock. Please talk to SiteLock and get this resolved. 

 http://moosangels.com/

![image](https://user-images.githubusercontent.com/1563192/57567894-06607800-73ae-11e9-9108-84ed91221ed7.png)

**Comment by pvenkateshnaidu** [comment]
Done but site lock pending
