### ISSUE TITLE
VirtualRealestates is not working. So let us move it to Future works

### ISSUE THREAD

**Issue by sharidass1408** [tirumalasrija/WebMobileZ-March2018#6]
We did not end up moving VirtualRealestates to future work as the client did not signup with us. Also remove the link 

![image](https://user-images.githubusercontent.com/1563192/57568071-445e9b80-73b0-11e9-8cd7-98aa15a6e140.png)

**Comment by pvenkateshnaidu** [comment]
Moved to future projects
