### ISSUE TITLE
CCIT has the wrong URL. Please change CCIT to its production link.

### ISSUE THREAD

**Issue by sharidass1408** [tirumalasrija/WebMobileZ-March2018#7]
CCIT is pointing to AVSConsultants. Please change it to its corresponding URL.

![2019-05-11_5-50-39](https://user-images.githubusercontent.com/1563192/57568110-d9619480-73b0-11e9-8ad5-00b2e93503a6.png)

**Comment by pvenkateshnaidu** [comment]
Updated
